owner: fanzyb # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Repository
    url: https://repo.kojedrive.workers.dev/
  - name: Personal Webstite
    url: https://www.fan.my.id
  - name: Link Website
    url: https://link.fan.my.id
status-website: # Status website (optional)
  cname: upptime.f-4.my.id # Custom domain CNAME
  name: Upptime # Status website title
