owner: fanzyb # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Personal Website
    url: https://fan.my.id
  - name: Link Website
    url: https://link.fan.my.id
  - name: Drive
    url: https://drive.manji.eu.org
  - name: Drive 2
    url: https://repo.kojedrive.workers.dev
assignees: # Users to assign downtime issues (optional)
status-website: # Status website (optional)
  cname: status.fan.my.id # Custom domain CNAME
  name: Live Status # Status website title
